apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  labels:
    app: web-terminal
  name: cluster-web-terminal
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    App: web-terminal
    Environment: dev
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cluster-readonly
rules:
- apiGroups:
  - ""
  - acme.cert-manager.io
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - app.k8s.io
  - apps
  - argoproj.io
  - authentication.istio.io
  - authentication.k8s.io
  - authorization.k8s.io
  - autoscaling
  - autoscaling.internal.knative.dev
  - batch
  - caching.internal.knative.dev
  - certificates.k8s.io
  - cert-manager.io
  - config.istio.io
  - coordination.k8s.io
  - crd.k8s.amazonaws.com
  - custom.metrics.k8s.io
  - dex.coreos.com
  - events.k8s.io
  - extensions
  - kubeflow.org
  - kubernetes-client.io
  - machinelearning.seldon.io
  - monitoring.coreos.com
  - mumoshu.github.io
  - networking.internal.knative.dev
  - networking.istio.io
  - networking.k8s.io
  - node.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - rbac.istio.io
  - scheduling.k8s.io
  - serving.knative.dev
  - serving.kubeflow.org
  - sparkoperator.k8s.io
  - storage.k8s.io
  - vpcresources.k8s.aws
  - webhook.cert-manager.io
  - external-secrets.io
  resources:
  - adapters
  - alertmanagers
  - apiservices
  - applications
  - appprojects
  - attributemanifests
  - authcodes
  - authorizationpolicies
  - authrequests
  - awssecrets
  - bindings
  - certificates
  - certificaterequests
  - certificatesigningrequests
  - challenges
  - clusterissuers
  - clusterrbacconfigs
  - clusterrolebindings
  - clusterroles
  - componentstatuses
  - configmaps
  - configurations
  - connectors
  - controllerrevisions
  - cronjobs
  - csidrivers
  - csinodes
  - customresourcedefinitions
  - daemonsets
  - deployments
  - deployments/scale
  - deployments/status
  - destinationrules
  - endpoints
  - eniconfigs
  - envoyfilters
  - events
  - experiments
  - externalsecrets
  - gateways
  - handlers
  - horizontalpodautoscalers
  - httpapispecbindings
  - httpapispecs
  - images
  - inferenceservices
  - ingresses
  - instances
  - issuers
  - jobs
  - leases
  - limitranges
  - localsubjectaccessreviews
  - meshpolicies
  - metrics
  - mutatingwebhookconfigurations
  - namespaces
  - networkpolicies
  - nodes
  - notebooks
  - oauth2clients
  - offlinesessionses
  - orders
  - passwords
  - persistentvolumeclaims
  - persistentvolumes
  - podautoscalers
  - poddefaults
  - poddisruptionbudgets
  - podmonitors
  - pods
  - pods/attach
  - pods/binding
  - pods/eviction
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/proxy
  - pods/status
  - podsecuritypolicies
  - podtemplates
  - policies
  - priorityclasses
  - profiles
  - prometheuses
  - prometheusrules
  - pytorchjobs
  - quotaspecbindings
  - quotaspecs
  - rbacconfigs
  - refreshtokens
  - replicasets
  - replicasets/scale
  - replicasets/status
  - replicationcontrollers
  - resourcequotas
  - revisions
  - rolebindings
  - roles
  - routes
  - rules
  - runtimeclasses
  - scheduledsparkapplications
  - scheduledworkflows
  - secrets
  - seldondeployments
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - serverlessservices
  - serviceaccounts
  - serviceentries
  - servicemonitors
  - servicerolebindings
  - serviceroles
  - services
  - sidecars
  - signingkeies
  - sparkapplications
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  - storageclasses
  - subjectaccessreviews
  - suggestions
  - templates
  - tfjobs
  - tokenreviews
  - trials
  - validatingwebhookconfigurations
  - viewers
  - virtualservices
  - volumeattachments
  - workflows
  - clusterexternalsecrets
  - clustersecretstores
  - externalsecrets
  - externalsecrets/status
  - clustersecretstores/status
  - secretstores
  verbs:
  - get
  - list
  - watch
  - patch
  - delete
  - update
  - deletecollection
  - create
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  name: web-terminal
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-web-terminal
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  labels:
    app: web-terminal
  name: web-terminal
  namespace: default
spec:
  ports:
  - name: web-terminal
    port: 80
    protocol: TCP
    targetPort: 7681
  selector:
    app: web-terminal
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  labels:
    app: web-terminal
  name: web-terminal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-terminal
  template:
    metadata:
      annotations:
        App: web-terminal
        Environment: dev
      labels:
        app: web-terminal
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kubeclever/web-terminal:IMAGE_TAG
        imagePullPolicy: Always
        name: web-terminal
        resources:
          limits:
            cpu: 160m
            memory: 512Mi
          requests:
            cpu: 40m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      securityContext:
        fsGroup: 65533
        runAsNonRoot: true
      serviceAccountName: cluster-web-terminal
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  labels:
    app: web-terminal
    name: web-terminal
  name: web-terminal-hpa
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-terminal
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    App: web-terminal
    Environment: dev
  name: web-terminal
  namespace: default
spec:
  gateways:
  - default/external-gateway
  hosts:
  - terminal....com
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: web-terminal.default.svc.cluster.local
        port:
          number: 80
